spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Restaurant?createDatabaseIfNotExist=true
    username: root
    password: "@gowthamidevi30"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080